name: Build & Deploy

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: codeberg-tiny

    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - uses: actions/checkout@v6

      - name: Install dependencies
        run: npm install

      - name: Running Eleventy
        run: npm run build:eleventy
          
      - name: Deploy to Cloudflare
        uses: https://github.com/cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy _site --project-name=aninus

      - name: Deploy to gh-pages
        uses: https://github.com/peaceiris/actions-gh-pages@v4
        with:
          publish_dir: _site
          external_repository: aninusmuffin/aninus.com
          deploy_key: ${{ secrets.GH_ACTIONS_DEPLOY_KEY }}
          cname: aninus.com