name: Mirror

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: codeberg-tiny

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Mirror to Github'
        uses: https://github.com/cssnr/mirror-repository-action@v1
        with:
          url: https://github.com/aninusmuffin/aninus.com
          create: true
          username: aninusmuffin
          password: ${{ secrets.MIRROR_TOKEN }}